
CREATE TABLE DETAILED_TIME (
                DETAILED_TIME_ID VARCHAR2(4) NOT NULL,
                MONTH_NUM NUMBER(2) NOT NULL,
                FISCAL_PERIOD VARCHAR2(4) NOT NULL,
                CONSTRAINT DETAILED_TIME_PK PRIMARY KEY (DETAILED_TIME_ID)
);


CREATE TABLE PLAN_DETAILS (
                PLAN_DETAILS_ID VARCHAR2(4) NOT NULL,
                NUM_OF_PHONES NUMBER(2) NOT NULL,
                MON_MINUTES NUMBER(5) NOT NULL,
                ROLLOVER_MINUTES NUMBER(4) NOT NULL,
                CONSTRAINT PLAN_DETAILS_PK PRIMARY KEY (PLAN_DETAILS_ID)
);


CREATE TABLE ADDRESS (
                ADDRESS_ID VARCHAR2(4) NOT NULL,
                STREET VARCHAR2(25) NOT NULL,
                CITY VARCHAR2(15) NOT NULL,
                ZIP NUMBER(6) NOT NULL,
                CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID)
);


CREATE TABLE STATUS (
                STATUS_KEY VARCHAR2(4) NOT NULL,
                NEW_CUSTOMER VARCHAR2(10) NOT NULL,
                NEW_ADDRESS VARCHAR2(20) NOT NULL,
                PAYMENT_OVERDUE FLOAT NOT NULL,
                CLOSED_PERIOD VARCHAR2(6) NOT NULL,
                CONSTRAINT STATUS_PK PRIMARY KEY (STATUS_KEY)
);


CREATE TABLE TIME (
                TIME_KEY VARCHAR2(4) NOT NULL,
                DETAILED_TIME_ID VARCHAR2(4) NOT NULL,
                MONTH VARCHAR2(3) NOT NULL,
                QUATER VARCHAR2(2) NOT NULL,
                YEAR NUMBER(4) NOT NULL,
                CONSTRAINT TIME_PK PRIMARY KEY (TIME_KEY)
);


CREATE TABLE CUSTOMER (
                CUSTOMER_KEY VARCHAR2(4) NOT NULL,
                ADDRESS_ID VARCHAR2(4) NOT NULL,
                CUSTOMER_NAME VARCHAR2(20) NOT NULL,
                CUSTOMER_CODE VARCHAR2(4) NOT NULL,
                FAMILY_SIZE NUMBER(2) NOT NULL,
                CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_KEY)
);


CREATE TABLE PLAN (
                PLAN_KEY VARCHAR2(4) NOT NULL,
                PLAN_DETAILS_ID VARCHAR2(4) NOT NULL,
                PLAN_NAME VARCHAR2(10) NOT NULL,
                PLAN_CODE VARCHAR2(4) NOT NULL,
                CONSTRAINT PLAN_PK PRIMARY KEY (PLAN_KEY)
);


CREATE TABLE USAGE_FACTS (
                USAGE_KEY VARCHAR2(4) NOT NULL,
                PLAN_KEY VARCHAR2(4) NOT NULL,
                TIME_KEY VARCHAR2(4) NOT NULL,
                CUSTOMER_KEY VARCHAR2(4) NOT NULL,
                STATUS_KEY VARCHAR2(4) NOT NULL,
                PLAN_MINUTES NUMBER(2) NOT NULL,
                OVERAGE_MINUTES NUMBER(2) NOT NULL,
                MON_ACCESS_CHRG NUMBER(4) NOT NULL,
                MON_OVERAGE_CHRG NUMBER(4) NOT NULL,
                VOICE_USAGE FLOAT NOT NULL,
                DATA_USAGE FLOAT NOT NULL,
                CONSTRAINT USAGE_FACTS_PK PRIMARY KEY (USAGE_KEY)
);


ALTER TABLE TIME ADD CONSTRAINT DETAILED_TIME_TIME_FK
FOREIGN KEY (DETAILED_TIME_ID)
REFERENCES DETAILED_TIME (DETAILED_TIME_ID)
NOT DEFERRABLE;

ALTER TABLE PLAN ADD CONSTRAINT PLAN_DETAILS_PLAN_FK
FOREIGN KEY (PLAN_DETAILS_ID)
REFERENCES PLAN_DETAILS (PLAN_DETAILS_ID)
NOT DEFERRABLE;

ALTER TABLE CUSTOMER ADD CONSTRAINT ADDRESS_CUSTOMER_FK
FOREIGN KEY (ADDRESS_ID)
REFERENCES ADDRESS (ADDRESS_ID)
NOT DEFERRABLE;

ALTER TABLE USAGE_FACTS ADD CONSTRAINT STATUS_USAGE_FACTS_FK
FOREIGN KEY (STATUS_KEY)
REFERENCES STATUS (STATUS_KEY)
NOT DEFERRABLE;

ALTER TABLE USAGE_FACTS ADD CONSTRAINT TIME_USAGE_FACTS_FK
FOREIGN KEY (TIME_KEY)
REFERENCES TIME (TIME_KEY)
NOT DEFERRABLE;

ALTER TABLE USAGE_FACTS ADD CONSTRAINT CUSTOMER_USAGE_FACTS_FK
FOREIGN KEY (CUSTOMER_KEY)
REFERENCES CUSTOMER (CUSTOMER_KEY)
NOT DEFERRABLE;

ALTER TABLE USAGE_FACTS ADD CONSTRAINT PLAN_USAGE_FACTS_FK
FOREIGN KEY (PLAN_KEY)
REFERENCES PLAN (PLAN_KEY)
NOT DEFERRABLE;
